### ISSUE TITLE
TODO's after Timber 2.0

### ISSUE THREAD

**Issue by Levdbas** [timber/starter-theme#147]
Now Timber 2.0 is released I went though this repo and written down the things that could use some love. I could create a PR for 1,2, 4,5 and cleanup the issues if I can get access to this repo as well :)

- [x] update readme file, it still suggests the plugin.
- [x] update examples in readme. Some are very old.
- [x] maybe create a release or remove older releases.
- [x] is this file needed at all? https://github.com/timber/starter-theme/blob/2.x/views/page-plugin.twig
- [x] cleanup issues in repo
- [x] Adding a [license](https://packagist.org/packages/upstatement/timber-starter-theme)?
- [x] Adding coding standard
- [x] Applying coding standard after merges
- [x] Fix PHPstan issues after merges
- [x] Overhauling the starter site class
- [x] PSR autoloading
- [ ] CI: auto run PHPCS and PHPUNIT
- [x] Update minimal PHP version to 8.1 in PHP unit tests and phpstan/phpcs

**Comment by szepeviktor** [comment]
Maybe choosing a coding standard?

**Comment by gchtr** [comment]
@Levdbas I just invited you as a maintainer, so I’d be happy if you could work on that list of issues. I have nothing to add ad the moment.

> * is this file needed at all? [`2.x`/views/page-plugin.twig](https://github.com/timber/starter-theme/blob/2.x/views/page-plugin.twig?rgh-link-date=2023-11-10T09%3A11%3A21Z)

You can find the relevant information here:
https://github.com/timber/starter-theme/blob/8d4f39c4efb3064cfe0d7cacf1d1d89711445e8d/footer.php#L2-L7

**Comment by gchtr** [comment]
I created a new release for 2.0: https://github.com/timber/starter-theme/releases/tag/2.0.0.

**Comment by Levdbas** [comment]
Hi @gchtr and @szepeviktor , A bunch of PR's have been created as a staring point for making the starter theme a bit more modern. I would like to have both your feedback if possible. Looking forward to the collaboration!
